### ISSUE TITLE
issue with cross account policy with assume role

### ISSUE THREAD

**Issue by oba11** [jonhadfield/sts#3]
Hi @jonhadfield,
Had some users who do assume role into another account through console which works fine.

Asked them to use this tool for programmatic access for some automation stuffs and interestingly got access denied. After some digging, discovered that the iam policy in the trusting role has a policy that requires mfa authentication like below

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": "*",
            "Resource": "*",
            "Condition": {
                "NumericLessThan": {
                    "aws:MultiFactorAuthAge": "14400"
                }
            }
        }
    ]
}
```
Using the mfa token to assume credential and using the assumed credential to assume the cross-account role worked.

What do you think about changing the implementation [here](https://github.com/jonhadfield/sts/blob/bb2cfb6668c879aafb49896b2ee8b78be268dff3/main.go#L343-L347) to something like that?

**Comment by jonhadfield** [comment]
Hi @oba11,
I found this description for that condition [here](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_mfa_configure-api-require.html):

> Duration—If you want to grant access only within a specified time after MFA authentication, use a numeric condition type to compare the aws:MultiFactorAuthAge key's age to a value (such as 3600 seconds). 

In using this app I guess the user could authenticate with the first AWS account using long-term credentials to get session token. That provides a temporary ID, secret and session token. They'd then run 'sts assume-role' to assume the role in the second account and, as long as it was done within four hours, that condition should be true?
Sorry if I misunderstand the question. Maybe a description of the change would help?

**Comment by oba11** [comment]
Thanks @jonhadfield for taking the time to the response and apologies for not replying sooner.

The description is right but the security implication of tying mfa condition with `sts:AssumeRole` is that its only valid when the user calls the policy (which is once) even if the session token age is greater than the mfa token age.

In the documentation, you are attaching the mfa token to the assume-role API call only while in one I was suggesting, you are attaching mfa token with user get credentials which in turn is attached to the assume-role API call (this is how console login works).

__Scenario 1__
Lets say a user wants to assume a role in another account and the mfa condition is tied to `sts:AssumeRole` in the trusting account. Once the role is assumed, users would always be able to do anything as long as the lifetime of the session token (this would work with [sts](https://github.com/jonhadfield/sts)

__Scenario 2__
Lets say a user want to assume a role in another account and the mfa condtion is tied to the role policy (like my example) in the trusting account. Any API call the `assumed role` make will be verified against the mfa auth age when the user switched to get session token

**Comment by jonhadfield** [comment]
Hi @oba11 
I've tested and [commented on the PR](https://github.com/jonhadfield/sts/pull/4#issuecomment-411175148).
After looking at the change and reading through this issue again, and reading AWS documentation I think I now understand the problem. 
I don't know exactly how an AWS Console login works behind the scenes but, if the user has logged in with MFA and the permission used to assume role another role requires MFA to be present (or less than X seconds), then it will be present and will work. 
In the same way, if the user had used the get-session-token call to obtain temporary credentials then, if they used MFA, their temporary credentials will be valid if their next API call, e.g. for STS to assume another role, requires MFA. As [this page]([url](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_mfa_configure-api-require.html)) says:
_"Because temporary credentials returned by GetSessionToken include MFA information, you can check for MFA in individual API operations made by the credentials. "_
I think this explains why your Scenario 1 works as expected.

For Scenario 2. This doesn't seem to be possible because (from the same page referenced above):
_"The temporary credentials returned by AssumeRole do not include MFA information in the context, so you cannot check individual API operations for MFA. This is why you must use GetSessionToken to restrict access to resources protected by resource-based policies."_ 

In your PR I believe you're trying to work around the MFA requirement blocking Scenario 2 by using the temporary credentials obtained by your initial assume-role to run 'get-session-token' with MFA.
Instead of adding get-session-token to assume role (which breaks a flow) is it not possible to do this:
1. User authenticates with long-term credentials and MFA to get temporary credentials including MFA details for subsequent API calls.
2. User assumes role in another account (successful because they have MFA detail with their previous authentication)
3. User uses gst in the second using the assumed credentials and now has new temporary credentials with MFA detail recorded
4. User can now assume role

I've not tried the above, so I'm not sure if it's possible. What we tend to do is not have an MFA requirement on the role in the final account but have a trust relationship that only allows that role to be assumed from the first account user/role where you have the MFA restriction imposed.

Could you attempt this scenario using the official awscli package to see if that achieves your goal? If it works, I'll take a look at how they implement it.

**Comment by oba11** [comment]
@jonhadfield Thanks alot for the detailed explanation, will give it a try and open a new PR.
Thanks again.

**Comment by oba11** [comment]
@jonhadfield Just checked again and seem to be fine with the approach of:
1. User authenticates with long-term credentials and MFA to get temporary credentials including MFA details for subsequent API calls.
2. User assumes role in another account (successful because they have MFA detail with their previous 2. authentication)
3. _User uses gst in the second using the assumed credentials and now has new temporary credentials with MFA detail recorded_

Scenario 3 won't be possible because `GetSessionToken` can't be called after a role has been assumed (Ref: [Doc](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_request.html#stsapi_comparison)), I think thats why the response from the `AssumeRole`(which contains the short-lived credentials should be credentials for that session. 

Tested below scenarios
1. User authenticates with long-term credentials and MFA to get temporary credentials including MFA details for subsequent API calls. `User can access resources in the account with output credentials`
2. User assumes role in another account (successful because they have MFA detail with their previous 2. authentication) `User can access resources in the assumed account with output credentials`

Please let me know if the PR can be re-opened without the use case 3. 
Thanks and apologies for the issues.
